server:
  port: 5000
spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: breaker
                fallbackUri: forward:/fallback
        - id: image-service
          uri: lb://image-service
          predicates:
            - Path=/public/**,/file/** # 假设所有图片请求都以/images开头
        - id: product-service-consumer
          uri: lb://product-service-consumer
          predicates:
            - Path=/product/**

        - id: shoppingcart-service
          uri: lb://shoppingcart-service
          predicates:
            - Path=/shoppingCart/**
          filters:
            - name: CircuitBreaker
              args:
                name: breaker
                fallbackUri: forward:/fallback
        - id: other-service
          uri: lb://other-service
          predicates:
            - Path=/resources/**,/comment/**,/address/**,/collect/**,/report/**
          filters:
            - name: CircuitBreaker
              args:
                name: breaker
                fallbackUri: forward:/fallback
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**,/alipay/**
          filters:
            - name: CircuitBreaker
              args:
                name: breaker
                fallbackUri: forward:/fallback


      #跨域处理，需要关闭具体微服务上的跨域设置，否则此设置无效
      globalcors: # 全局的跨域配置
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        # options请求 就是一种询问服务器是否浏览器可以跨域的请求
        # 如果每次跨域都有询问服务器是否浏览器可以跨域对性能也是损耗
        # 可以配置本次跨域检测的有效期maxAge
        # 在maxAge设置的时间范围内，不去询问，统统允许跨域
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: # 允许哪些网站的跨域请求
              - "*"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*"    # 允许在请求中携带的头信息
            allowCredentials: true    # 允许在请求中携带cookie
            maxAge: 360000            # 本次跨域检测的有效期(单位毫秒)
            # 有效期内，跨域请求不会一直发option请求去增大服务器压力

eureka:
  client:
    service-url:
      defaultZone: http://localhost:2500/eureka/
jwt:
  SING: "sunNeverSets" #密钥
  expireTime: 30 #token有效时间 (分钟)