server:
  port: 2801
spring:
  application:
    name: shoppingcart-service
  datasource:
    url: jdbc:mysql://localhost:3306/mi?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: tda6060g

eureka:
  client:
    service-url:
      defaultZone: http://localhost:2500/eureka/